services:

  database:
    container_name: database
    image: postgres:15.3-alpine3.17
    restart: on-failure
    environment:
      - POSTGRES_USER="sa"
      - POSTGRES_PASSWORD="sa"
      - POSTGRES_DB="postgres"
    ports:
      - "5432:5432"
      