services: 
  joxit:
    image: joxit/docker-registry-ui:latest
    container_name: docker-registry-ui
    restart: always
    # Uncomment the following lines if you want to use Traefik
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.docker.network=traefik_network"
    #   - "traefik.http.routers.registry_ui.entrypoints=websecure"
    #   - "traefik.http.routers.registry_ui.rule=Host(`my-domain-exemple.com`)"
    #   - "traefik.http.services.registry_ui.loadbalancer.server.port=80"
    #   - "traefik.http.routers.registry_ui.tls=true"
    #   - "traefik.http.routers.registry_ui.tls.certresolver=production"
    environment:
      - NGINX_PROXY_PASS_URL=http://docker-registry:5000 # URL of your registry
      - DELETE_IMAGES=true # Enable the delete button
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Home Server Registry # Title of your registry
    ports:
      - 80:80
    # networks:
    #   - traefik_network